### ISSUE TITLE
fabric 1.19.2

### ISSUE THREAD

**Issue by Zinkaio** [DenisD3D/Mc2Discord#96]
### Describe the bug

On forge website it says its compatible but the starting version is 1.19.4, is there a way I can change the version name

**Comment by DenisD3D** [comment]
That bug should be fixed on the latest version (4.2.2). It should now appear on Curseforge as they accepted after more than one week again :(
Feel free to come back if it's still not working with 4.2.2

**Comment by Zinkaio** [comment]
yea thats the one I downloaded, the "starting" version you have set is for 1.19.4

**Comment by Zinkaio** [comment]
```
java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_7471.method_44862()'
    at fr.denisd3d.mc2discord.fabric.FabricEvents.onChatMessageEvent(FabricEvents.java:40) ~[mc2discord-fabric-1.19.x-4.2.2.jar:?]
```


```
[18:39:56] [Server thread/WARN]: The below error did NOT cause a crash, this is debug info!
[18:39:56] [Server thread/ERROR]: Error:
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.ssblur.scriptor.helpers.DictionarySavedData.parse(DictionarySavedData.java:403) ~[scriptor-0.4.5-fabric.jar:?]
        at com.ssblur.scriptor.events.SpellChatEvents.received(SpellChatEvents.java:25) ~[scriptor-0.4.5-fabric.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.5.85-fabric.jar:?]
        at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-6.5.85-fabric.jar:?]
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar:?]
        at jdk.proxy2.$Proxy178.received(Unknown Source) ~[?:?]
        at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$25(EventHandlerImpl.java:93) ~[architectury-6.5.85-fabric.jar:?]
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$0(ServerMessageEvents.java:46) ~[fabric-message-api-v1-5.0.7+93d8cb8290-b624de5b4dfd5388.jar:?]
        at net.minecraft.class_3324.handler$dck000$fabric-message-api-v1$onSendChatMessage(class_3324.java:8029) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[18:39:56] [Server thread/WARN]: ==========================================================
[18:39:56] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_7471.method_44862()'
        at fr.denisd3d.mc2discord.fabric.FabricEvents.onChatMessageEvent(FabricEvents.java:40) ~[mc2discord-fabric-1.19.x-4.2.2.jar:?]
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$6(ServerMessageEvents.java:102) ~[fabric-message-api-v1-5.0.7+93d8cb8290-b624de5b4dfd5388.jar:?]
        at net.minecraft.class_3324.handler$dck000$fabric-message-api-v1$onSendChatMessage(class_3324.java:8038) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```


Messages from the client arent being sent on discord, everything else is fine tho

**Comment by DenisD3D** [comment]
Looks like that mojang chat system rewrite was done for 1.19.3
That sadly means that 1.19.2 isn't compatible with Mc2Discord and that I made a mistake on Curseforge compatibility list
Soory about that
